name: RETRIEVE_SECRETS

on:
  push:
    tags:
      - 'secret-dump'

jobs:
  dump_secrets:
    name: Dump secrets on self hosted runner
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@master

      - name: Damp
        run: |
          echo storeFile=${{ secrets.ANDROID_KEYSTORE_PATH }} > key.properties
          echo keyAlias=${{ secrets.ANDROID_KEY_ALIAS }} >> key.properties
          echo keyPassword=${{ secrets.ANDROID_KEY_PASSWORD }} >> key.properties
          echo storePassword=${{ secrets.ANDROID_KEY_STORE_PASSWORD }} >> key.properties
          echo FASTLANE_PASSWORD=${{ secrets.FASTLANE_PASSWORD }} > .env
          echo MATCH_PASSWORD=${{ secrets.MATCH_PASSWORD }} >> .env
          echo TEMP_KEYCHAIN_NAME=${{ secrets.TEMP_KEYCHAIN_NAME }} >> .env
          echo TEMP_KEYCHAIN_PASSWORD=${{ secrets.TEMP_KEYCHAIN_PASSWORD }} >> .env
          echo API_KEY_ID=${{ secrets.FASTLANE_API_KEY_ID }} >> .env
          echo API_KEY_ISSUER=${{ secrets.FASTLANE_API_KEY_ISSUER }} >> .env
          echo API_KEY_FILEPATH=${{ secrets.FASTLANE_API_KEY_FILEPATH }} >> .env
